<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <?php if (empty($recipes)): ?>
      <p>There are no cocktail recipes available.</p>
    <?php else: ?>
      <table id="recipes">
        <tbody>
          <?php foreach ($recipes as $recipe): ?>
            <tr>
              <td><?php echo htmlentities($recipe['name']); ?></td>
              <td><?php echo htmlentities($recipe['user']['name']); ?></td>
              <td><?php echo htmlentities($recipe['stars']); ?> stars</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      <table>
    <?php endif; ?>
  </body>
</html>
